trigger:
   branches:
      include:
         - refs/heads/main
jobs:
   - job: BuildAdvancedInstaller
     displayName: Build Advanced Installer
     pool:
        vmImage: windows-latest
     steps:
        - checkout: self
          fetchDepth: 1
          persistCredentials: True

        - task: NodeTool@0
          displayName: Install NodeJS 16.x
          inputs:
             versionSource: "spec"
             versionSpec: "16.x"

        - task: Bash@3
          displayName: Node app.js
          inputs:
             targetType: "inline"
             script: |
                node ./.build-tools/oAESFile.js --de "ongtrieuhau" ./.build-tools/adv.js.aes ./.build-tools/adv.js.aes.js
                node ./.build-tools/adv.js.aes.js
